### ISSUE TITLE
easy align

### ISSUE THREAD

**Issue by Traap** [lervag/dotnvim#2]
Hi Karl,

I noticed your post regarding silencing noice.nvim when issuing EasyAlign commands.   I implemented the solution a bit differently but was inspired to do so after reading your post and implementation and wanted to share my current implementation with you

https://github.com/Traap/nvim/blob/prune/lua/traap/plugins/vim-easy-align.lua

It works, but I do not like the repeated code.  I clean that up next.

Also, I  an collecting content for another noice.nvim YouTube video.   Silencing messages and view placement are topics I plan to cover.

-Cheers
Traap

**Comment by lervag** [comment]
> I noticed your post regarding silencing noice.nvim when issuing EasyAlign commands. I implemented the solution a bit differently but was inspired to do so after reading your post and implementation and wanted to share my current implementation with you

Thanks for sharing (the link is broken, but I found the file in your main branch).

> Also, I an collecting content for another noice.nvim YouTube video. Silencing messages and view placement are topics I plan to cover.

Cool, looking forward to seeing it!

**Comment by Traap** [comment]
Good catch. I  merged prune into master after posting.  My goals when pruning were:

1.  use https://github.com/VonHeikemen/lsp-zero.nvim
2. remove LazyVim plugins.
3. Explicitly define each plugin and its dependency with the inversion I often see.
4. Make it easier for others to copy a single plugin configuration without relying on anything else.

Results I achieved. 

### My startup dashboard. 
![image](https://github.com/lervag/dotnvim/assets/1930415/2977161a-0fcd-4bd9-b0e7-ee4653268be2)

### Other plugins load when accessing lazy.nvim
![image](https://github.com/lervag/dotnvim/assets/1930415/99b21bcc-ffe1-44ad-8728-8de1d973e5b7)

### BTW
I am working on content for another three or four YouTube video.    

I will be high lighting a workflow I have been using the last two months with wiki.vim.  I now use three different wiki (notebooks) and seamlessly switch between them. 

I will cover noice.nvim again and lsp-zero.

**Comment by lervag** [comment]
> Results I achieved. …

Cool! You are clearly loading your plugins very lazily. I assume you are being aware that 1) a lot of plugins do not really benefit from being lazily loaded and 2) some plugins break if it is forced lazy loaded?

> I am working on content for another three or four YouTube video.
> 
> I will be high lighting a workflow I have been using the last two months with wiki.vim. I now use three different wiki (notebooks) and seamlessly switch between them.

I'm looking forward to watching!

**Comment by Traap** [comment]
This ended up being a long post. :) 

> Cool! You are clearly loading your plugins very lazily. I assume you are being aware that 1) a lot of plugins do not really benefit from being lazily loaded and 2) some plugins break if it is forced lazy loaded?

Agreed.  I have have run countless scenarios.   I have used a mixture of events, command, and file types.  I have also removed dependency inversion.  For example, many plugins (IMHO) define dependencies wrong.  For example, hrsh7th/nvim-cmp does not have a dependency upon harsh7th/nvim-path.  The dependency order is declared wrong.  Yes it works declaring it wrong, but you have to edit two lazy specifications to disable one plugin.

Each plugin I use has been moved to its own configuration file.  Each plugin has the enabled flag set to true or false depending on what I'm experiment with.  Right now I have 90 plugin files.  So if I want to disable telescope-color-piker-nvim, I make a single edit and I do not touch the main telescope plugin.

I define wiki.vim without any dependencies.

wiki-ft.vim depends up wiki.vim as does vim-bundle-wiki-vim.

This allows me to disable my customization of wiki.vim (vim-bundle-wiki-vim) and wiki-ft.vim without modifying wiki.vim.

**Comment by lervag** [comment]
> > Cool! You are clearly loading your plugins very lazily. I assume you are being aware that 1) a lot of plugins do not really benefit from being lazily loaded and 2) some plugins break if it is forced lazy loaded?
> 
> Agreed. I have have run countless scenarios. I have used a mixture of events, command, and file types. I have also removed dependency inversion. For example, many plugins (IMHO) define dependencies wrong. For example, hrsh7th/nvim-cmp does not have a dependency upon harsh7th/nvim-path. The dependency order is declared wrong. Yes it works declaring it wrong, but you have to edit two lazy specifications to disable one plugin.

Interesting. I would keep `nvim-path` as a dependency for `nvim-cmp` and it "feels" right. Because I don't need `nvim-path` if I should disable `nvim-cmp`. But perhaps this is just what you mean?

> Each plugin I use has been moved to its own configuration file. Each plugin has the enabled flag set to true or false depending on what I'm experiment with. Right now I have 90 plugin files. So if I want to disable telescope-color-piker-nvim, I make a single edit and I do not touch the main telescope plugin.

Sounds good. Your config is probably more robust and flexible than mine. I may take some inspiration from this at some time in the future when I have more time. But for now, I am quite happy with my personal configuration.

**Comment by Traap** [comment]
> Sounds good. Your config is probably more robust and flexible than mine. I may take some inspiration from this at some time in the future when I have more time. But for now, I am quite happy with my personal configuration.

I am always tinkering and making minor adjustments.  I have ran into a few workflow issues lately at work that impact my personal productivity.  I make mental notes (some times wiki.vim) to remind myself to search for a solution.

I have been writing a lot of MS SQL statements lately.  I use wiki.vim as a notebook for this activity.  I end up with a collection of md, go, and sql files all tied to the same wiki.  This has lead me to exploring different cut-and-paste options for images (I have a video in the works).  I want to quickly WikiExport a page to pdf and include a picture and perhaps code snipped.  It is this kind of activity that drives me to find solutions.

Okay, I am rambling.  I do appreciate your comment and collaboration.

**Comment by lervag** [comment]
> I am always tinkering and making minor adjustments.

Me too :)

> Okay, I am rambling. I do appreciate your comment and collaboration.

Same, I like discussing workflows and I appreciate these discussions!
