### ISSUE TITLE
nvims support

### ISSUE THREAD

**Issue by Traap** [lervag/dotnvim#3]
Hi Karl,

This repository has been added to https://github.com/Traap/nvims

### nvims
1.  Installs in less than 5 mins.
2.  Does not conflict with Neovim or Vim installation you have.
3.  lervag/nvims is now supported

### nvims from the command line
![image](https://github.com/lervag/dotnvim/assets/1930415/3aa98a9f-f91a-43cb-8165-feb187544f1b)

### nvim-lervag to select lervag configutation.
![image](https://github.com/lervag/dotnvim/assets/1930415/3c287e57-64fd-4045-9a56-938c92296b21)

### Excellent startup time.
![image](https://github.com/lervag/dotnvim/assets/1930415/dc8f88b7-4b76-4f36-8d47-eea2004d0b2c)

**Comment by lervag** [comment]
Cool! And yes, I'm very fond of having a short startup time! Reaching <50 ms was nice and I definitely do notice the difference between my older configs that were ~200 ms or so. In my workflow, I open new neovim instances very often, so having them appear more or less instantly is a killer feature for me.

I don't think my config is necessarily very interesting as it is very personalized. But I like the idea of making it very easy to test different setups. It seems like it can be very helpful for people investigating different options. I believe your project should be of interest to a lot of people in the community. Have you considered sharing this on Reddit (r/neovim)?

**Comment by lervag** [comment]
(Closing the issue since I'll not "act" on anything here, but feel free to continue the discussion.)

**Comment by Traap** [comment]
I do not use Reddit very often.  I had not considered "promoting" myself there.  I will defiantly checkout r/neovim.  Thank you for the tip.

**Comment by lervag** [comment]
> I do not use Reddit very often. I had not considered "promoting" myself there. I will defiantly checkout r/neovim. Thank you for the tip.

I don't like Reddit much, but I do appreciate the neovim community on r/neovim. 👍🏻

**Comment by Traap** [comment]
I posted to  nvims and lazy-zero to reddit.   lazy-zero covers the lsp-zero plugin.  The author already replied to my post and offered a suggestion that made lazy-zero better.

https://github.com/Traap/lazy.zero
